# Resource Allocation Code Demo

The Food Bank of the Southern Tier (FBST) is a member of Feeding America, focused on providing food security for people with limited financial resources, and serves six counties and nearly 4,000 square miles in the New York.  Under normal operations (non COVID times), the Mobile Food Pantry program is among the main activities of the FBST.  The goal of the service is to make nutritious and healthy food more accessible to people in underserved communities.  Even in areas where other agencies provide assistance, clients may not always have access to food due to limited public transportation options, or because those agencies are only open hours or days per work.

Here we do a sample experiment testing out some of the existing and developed algorithms against a randomized heuristic.

In [1]:
import or_suite
import numpy as np

import copy

import os
from stable_baselines3.common.monitor import Monitor
from stable_baselines3 import PPO
from stable_baselines3.ppo import MlpPolicy
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.evaluation import evaluate_policy
import pandas as pd


import gym

In [2]:
# Getting out configuration parameter for the environment
CONFIG =  or_suite.envs.env_configs.resource_allocation_simple_config


# Specifying training iteration, epLen, number of episodes, and number of iterations
epLen = CONFIG['num_rounds']
nEps = 300
numIters = 2


# Configuration parameters for running the experiment
DEFAULT_SETTINGS = {'seed': 1, 
                    'recFreq': 1, 
                    'dirPath': '../data/resource/', 
                    'deBug': False, 
                    'nEps': nEps, 
                    'numIters': numIters, 
                    'saveTrajectory': True, # save trajectory for calculating additional metrics
                    'epLen' : epLen,
                    'render': False,
                    'pickle': False # indicator for pickling final information
                    }

resource_env = gym.make('Resource-v0', config=CONFIG)
mon_env = Monitor(resource_env)


In [3]:
agents = { # 'SB PPO': PPO(MlpPolicy, mon_env, gamma=1, verbose=0, n_steps=epLen),
#'Random': or_suite.agents.rl.random.randomAgent(),
#'Equal': or_suite.agents.resource_allocation.equal_allocation.equalAllocationAgent(epLen, CONFIG),
#'FixedThreshold': or_suite.agents.resource_allocation.fixed_threshold.fixedThresholdAgent(epLen, CONFIG),
'HopeGuardrail': or_suite.agents.resource_allocation.hope_guardrail.hopeguardrailAgent(epLen, CONFIG, .5)
}

Mean and variance endomwnets:
[[1.964 2.024 1.999 2.008 1.992 2.006 2.046 1.962 1.998 2.011]
 [3.016 3.035 3.049 2.901 2.966 3.055 3.043 2.99  2.959 3.025]
 [3.959 4.016 4.013 4.051 4.032 4.005 4.005 3.923 3.93  4.042]] [[0.914704 1.129424 1.038999 0.949936 1.021936 1.031964 1.075884 0.952556
  1.003996 0.942879]
 [1.963744 2.007775 1.980599 1.999199 1.916844 2.009975 2.043151 1.9719
  2.007319 2.090375]
 [2.961319 3.063744 2.952831 2.978399 3.112976 2.696975 3.056975 3.053071
  3.0471   2.724236]]


# Step 5: Run Simulations

Run the different heuristics in the environment

In [4]:
path_list_line = []
algo_list_line = []
path_list_radar = []
algo_list_radar= []
for agent in agents:
    print(agent)
    DEFAULT_SETTINGS['dirPath'] = '../data/resource_'+str(agent)+'/'
    if agent == 'SB PPO':
        or_suite.utils.run_single_sb_algo(mon_env, agents[agent], DEFAULT_SETTINGS)
    elif agent == 'AdaQL' or agent == 'Unif QL' or agent == 'AdaMB' or agent == 'Unif MB':
        or_suite.utils.run_single_algo_tune(resource_env, agents[agent], scaling_list, DEFAULT_SETTINGS)
    else:
        or_suite.utils.run_single_algo(resource_env, agents[agent], DEFAULT_SETTINGS)

    path_list_line.append('../data/resource_'+str(agent))
    algo_list_line.append(str(agent))
    if agent != 'SB PPO':
        path_list_radar.append('../data/resource_'+str(agent)+'/')
        algo_list_radar.append(str(agent))

fig_path = '../figures/'
fig_name = 'resource'+'_line_plot'+'.pdf'
or_suite.plots.plot_line_plots(path_list_line, algo_list_line, fig_path, fig_name, int(nEps / 40)+1)        
        
additional_metric = {}
fig_name = 'resource'+'_radar_plot'+'.pdf'
or_suite.plots.plot_radar_plots(path_list_radar, algo_list_radar,
fig_path, fig_name,
additional_metric
)




        


HopeGuardrail
Lower and Upper Solutions:
[[0.      0.17969]
 [0.      0.17969]
 [0.23059 0.     ]] [[0.      0.26279]
 [0.      0.26279]
 [0.33723 0.     ]]
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 10.0, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 9.30823040008545, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.847049713134766, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.023409843444824, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 6.94527006149292, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.33723, 0.0]]
Box(0.0, 6.079969882965088, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.33723, 0.0]]
Box(0.0, 5.742740154266357, (3, 2), float32)
allocation 
 [[0.0, 0.26279], [0.0, 0.26279], [0.33723, 0.0]]
Box(0.0, 4.393819808959961, (3, 2), float32)
al

 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 5.148369789123535, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 4.249919891357422, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 3.7740700244903564, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 2.851710081100464, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 1.913949966430664, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 0.6561200022697449, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 9.30823040008545, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.385869979858398, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.155280113220215, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0

/Users/jren/opt/anaconda3/envs/ORSuite/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py:167: UserWarning: You are solving a parameterized problem that is not DPP. Because the problem is not DPP, subsequent solves will not be faster than the first one. For more information, see the documentation on Discplined Parametrized Programming, at
	https://www.cvxpy.org/tutorial/advanced/index.html#disciplined-parametrized-programming
  warnings.warn(dpp_error_msg)
/Users/jren/Desktop/GitHub/ORSuite/or_suite/envs/resource_allocation/resource_allocation.py:114: RuntimeWarning: divide by zero encountered in log
  [old_type[theta]*np.log(self.utility_function(allocation[theta, :],


 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 1.8573299646377563, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 9.30823040008545, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.616459846496582, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.023409843444824, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 6.406199932098389, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 5.507750034332275, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 4.465839862823486, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 3.7108500003814697, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 2.4530200958251953, (3, 2), float32)
allocation 
 [[0.11091428571428578, 0.26279], [

 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 9.30823040008545, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 8.385869979858398, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 7.6940999031066895, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 7.0023298263549805, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 5.687439918518066, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 4.788990020751953, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 3.7740700244903564, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 3.0822999477386475, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969], [0.23059, 0.0]]
Box(0.0, 1.4681700468063354, (3, 2), float32)
allocation 
 [[0.0, 0.17969], [0.0, 0.17969],

AssertionError: 